export const CONFIG_JWT_SECRET = 'JWT_SECRET';
export const CONFIG_JWT_ACCESS_EXPIRY = 'JWT_ACCESS_EXPIRY';

export const CONFIG_DATABASE_HOST = 'DATABASE_HOST';
export const CONFIG_DATABASE_PORT = 'DATABASE_PORT';
export const CONFIG_DATABASE_USERNAME = 'DATABASE_USERNAME';
export const CONFIG_DATABASE_PASSWORD = 'DATABASE_PASSWORD';
export const CONFIG_DATABASE_NAME = 'DATABASE_NAME';
export const CONFIG_DATABASE_TYPE = 'DATABASE_TYPE';

export const CONFIG_CORS_ORIGINS = 'CORS_ORIGINS';

export const CONFIG_ENABLE_SWAGGER = 'ENABLE_SWAGGER';
