export const ENV_JWT_SECRET = 'JWT_SECRET';
export const ENV_JWT_ACCESS_EXPIRY = 'JWT_ACCESS_EXPIRY';

export const ENV_DATABASE_HOST = 'DATABASE_HOST';
export const ENV_DATABASE_PORT = 'DATABASE_PORT';
export const ENV_DATABASE_USERNAME = 'DATABASE_USERNAME';
export const ENV_DATABASE_PASSWORD = 'DATABASE_PASSWORD';
export const ENV_DATABASE_NAME = 'DATABASE_NAME';
export const ENV_DATABASE_TYPE = 'DATABASE_TYPE';

export const ENV_CORS_ORIGINS = 'CORS_ORIGINS';

export const ENV_ENABLE_SWAGGER = 'ENABLE_SWAGGER';
