/** Server Settings */
export const ENV_API_PREFIX = 'API_PREFIX';
export const ENV_API_VERSION = 'API_VERSION';
export const ENV_CORS_ORIGINS = 'CORS_ORIGINS';
export const ENV_ENABLE_SWAGGER = 'ENABLE_SWAGGER';
export const ENV_ENVIRONMENT = 'ENVIRONMENT';
export const ENV_GENERATE_SWAGGER_JSON = 'GENERATE_SWAGGER_JSON';
export const ENV_JWT_ACCESS_EXPIRATION_TIME = 'JWT_ACCESS_EXPIRATION_TIME';
export const ENV_JWT_REFRESH_EXPIRATION_TIME = 'JWT_REFRESH_EXPIRATION_TIME';
export const ENV_JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET';
export const ENV_JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET';
export const ENV_SERVER_HOST = 'SERVER_HOST';
export const ENV_SERVER_PORT = 'SERVER_PORT';
export const ENV_SWAGGER_JSON_FILE = 'SWAGGER_JSON_FILE';

export const ENV_DATABASE_HOST = 'DATABASE_HOST';
export const ENV_DATABASE_PORT = 'DATABASE_PORT';
export const ENV_DATABASE_USERNAME = 'DATABASE_USERNAME';
export const ENV_DATABASE_PASSWORD = 'DATABASE_PASSWORD';
export const ENV_DATABASE_NAME = 'DATABASE_NAME';
export const ENV_DATABASE_TYPE = 'DATABASE_TYPE';
export const ENV_DATABASE_PATH = 'DATABASE_PATH';
export const ENV_DATABASE_LOGGING_ENABLED = 'DATABASE_LOGGING_ENABLED';
export const ENV_DATABASE_SYNCHRONIZE = 'DATABASE_SYNCHRONIZE';

export const ENV_SENTRY_DSN = 'SENTRY_DSN';

export const ENV_SOCIAL_GOOGLE_ENABLED = 'SOCIAL_GOOGLE_ENABLED';
export const ENV_SOCIAL_GOOGLE_CLIENT_ID = 'SOCIAL_GOOGLE_CLIENT_ID';
export const ENV_SOCIAL_GOOGLE_CLIENT_SECRET = 'SOCIAL_GOOGLE_CLIENT_SECRET';

export const ENV_EMAIL_ENABLED = 'EMAIL_ENABLED';
export const ENV_EMAIL_HOST = 'EMAIL_HOST';
export const ENV_EMAIL_PORT = 'EMAIL_PORT';
export const ENV_EMAIL_USER = 'EMAIL_USER';
export const ENV_EMAIL_PASSWORD = 'EMAIL_PASSWORD';
export const ENV_EMAIL_TEMPLATE_DIR = 'EMAIL_TEMPLATE_DIR';
export const ENV_EMAIL_PARTIALS_DIR = 'EMAIL_PARTIALS_DIR';
export const ENV_EMAIL_IGNORE_TLS = 'EMAIL_IGNORE_TLS';
export const ENV_EMAIL_SECURE = 'EMAIL_SECURE';
export const ENV_EMAIL_REQUIRE_TLS = 'EMAIL_REQUIRE_TLS';
export const ENV_EMAIL_DEBUG = 'EMAIL_DEBUG';
export const ENV_EMAIL_DEFAULT_NAME = 'EMAIL_DEFAULT_NAME';
export const ENV_EMAIL_DEFAULT_EMAIL = 'EMAIL_DEFAULT_EMAIL';
