---
name: 'Meta Sync labels'

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['.github/labels.yaml']

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Sync Labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
        with:
          config-file: .github/labels.yaml
          token: '${{ secrets.GITHUB_TOKEN }}'
          delete-other-labels: true
